/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.Cadastrar;

import DAO.CategoriaDAO;
import DAO.ClassificacaoDAO;
import DAO.ClienteDAO;
import DAO.Conexao;
import DAO.FilmeDAO;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import modelo.Categoria;
import modelo.Classificacao;
import modelo.Cliente;
import modelo.Filme;

/**
 *
 * @author MANUEL GUSTAVO
 */
public class CadastrarFilme extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarFilme
     */
    public CadastrarFilme() {
        initComponents();
        AtualizaCombo();
        AtualizaCombo2();
        
    }
    //CadFilme
    
    

    //AtualizaCombo
    public void AtualizaCombo(){
        Connection con = Conexao.AbrirConexao();
        CategoriaDAO sql = new CategoriaDAO(con);
        List<Categoria> lista = new ArrayList<>();
        lista = sql.ListarComboCategoria();
        jCB_Nome.addItem("");
        
        for(Categoria b : lista){
            jCB_Nome.addItem(b.getNome());
        }
       Conexao.FecharConexao(con);
    }
    
    public void AtualizaCombo2(){
        Connection con = Conexao.AbrirConexao();
        ClassificacaoDAO sql = new ClassificacaoDAO(con);
        List<Classificacao> lista = new ArrayList<>();
        lista = sql.ListarComboClassificacao();
        jCB_Nome2.addItem("");
        
        for(Classificacao b : lista){
            jCB_Nome2.addItem(b.getNome());
        }
       Conexao.FecharConexao(con);
    }
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTF_Duracao = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        tfCapa = new javax.swing.JTextField();
        jTF_Ano = new javax.swing.JTextField();
        jTF_Filme = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jCB_Nome2 = new javax.swing.JComboBox<>();
        jTF_codigo = new javax.swing.JTextField();
        jCB_Nome = new javax.swing.JComboBox<>();
        jTF_codigo2 = new javax.swing.JTextField();
        btCapa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ibCapa = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("CÓDIGO:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Star Jedi", 1, 18)); // NOI18N
        jLabel2.setText("cadastro de filmes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(220, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 10, 700, 70);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("TÍTULO:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 140, 70, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("DURAÇÃO:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(230, 180, 90, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("CAPA 270 X 190");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(500, 100, 120, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("CLASSIFICAÇÃO:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 260, 110, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText("CAPA:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 300, 70, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setText("ANO:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 180, 70, 20);

        jTF_Duracao.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jTF_Duracao);
        jTF_Duracao.setBounds(310, 180, 90, 30);

        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(100, 100, 90, 30);

        tfCapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCapaActionPerformed(evt);
            }
        });
        getContentPane().add(tfCapa);
        tfCapa.setBounds(100, 300, 220, 30);
        getContentPane().add(jTF_Ano);
        jTF_Ano.setBounds(100, 180, 90, 30);
        getContentPane().add(jTF_Filme);
        jTF_Filme.setBounds(100, 140, 300, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 0));
        jLabel10.setText("CATEGORIA:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 220, 90, 20);

        jCB_Nome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_Nome2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCB_Nome2);
        jCB_Nome2.setBounds(210, 260, 190, 30);
        getContentPane().add(jTF_codigo);
        jTF_codigo.setBounds(140, 220, 50, 30);

        jCB_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_NomeActionPerformed(evt);
            }
        });
        getContentPane().add(jCB_Nome);
        jCB_Nome.setBounds(210, 220, 190, 30);
        getContentPane().add(jTF_codigo2);
        jTF_codigo2.setBounds(140, 260, 50, 30);

        btCapa.setText("OK");
        btCapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapaActionPerformed(evt);
            }
        });
        getContentPane().add(btCapa);
        btCapa.setBounds(330, 300, 47, 30);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jButton2.setText("CANCELAR");

        btSalvar.setText("CADASTRAR");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        jButton4.setText("LIMPAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 340, 700, 70);

        ibCapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/DVD_VIDEO_logo.png"))); // NOI18N
        getContentPane().add(ibCapa);
        ibCapa.setBounds(420, 130, 270, 190);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 0));
        jLabel11.setText("CÓDIGO:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 100, 70, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pedue\\Downloads\\NetBeansProjects\\Locadora\\src\\imagens\\fundo cad filme.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCB_Nome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_Nome2ActionPerformed
        Connection con = Conexao.AbrirConexao();
        ClassificacaoDAO sql = new ClassificacaoDAO(con);
        List<Classificacao> lista = new ArrayList<>();
        String nome = jCB_Nome2.getSelectedItem().toString();
        
        lista = sql.ConsultaCodigoClassificacao(nome);
        
        for(Classificacao b : lista){
            int a = b.getCodigo();
            jTF_codigo2.setText("" + a);
        }
        Conexao.FecharConexao(con);
    }//GEN-LAST:event_jCB_Nome2ActionPerformed

    private void jCB_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_NomeActionPerformed
        Connection con = Conexao.AbrirConexao();
        CategoriaDAO sql = new CategoriaDAO(con);
        List<Categoria> lista = new ArrayList<>();
        String nome = jCB_Nome.getSelectedItem().toString();
        
        lista = sql.ConsultaCodigoCategoria(nome);
        
        for(Categoria b : lista){
            int a = b.getCodigo();
            jTF_codigo.setText("" + a);
        }
        Conexao.FecharConexao(con);
    }//GEN-LAST:event_jCB_NomeActionPerformed

    private void btCapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapaActionPerformed
        try{
            JFileChooser foto = new JFileChooser();
            foto.setCurrentDirectory(new File("/C:/Video Locadora/Pictures/"));
            foto.setDialogTitle("Carregar Capa");
            foto.showOpenDialog(this);
            String a = "" + foto.getSelectedFile().getName();
            tfCapa.setText(a);
            ibCapa.setIcon(new ImageIcon("/C:/Video Locadora/Pictures/"+ tfCapa.getText() + "/"));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Não foi possível carregar a capa");
        }
    }//GEN-LAST:event_btCapaActionPerformed

    private void tfCapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCapaActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
           String Titulo = jTF_Filme.getText();
           String ano = jTF_Ano.getText();
           String Duracao = jTF_Duracao.getText();
            if(Titulo.equals("") || ano.equals("") || Duracao.equals("")){
               JOptionPane.showMessageDialog(null, "nenhum campo pode esta vazio", "Video Locadora", JOptionPane.WARNING_MESSAGE);
               
           }else{
               Connection con = Conexao.AbrirConexao();
               FilmeDAO sql = new FilmeDAO(con);
               Filme a = new Filme();
               
               a.setTitulo(Titulo);
               a.setAno(ano);
               a.setDuracao(Duracao);
              
               sql.Inserir_Filme(a);
               Conexao.FecharConexao(con);
               
               jTF_Filme.setText("");
               jTF_Ano.setText("");
               jTF_Duracao.setText("");
               JOptionPane.showMessageDialog(null, "Cadastro realizado com Sucesso", "Video Locadora", JOptionPane.INFORMATION_MESSAGE);
               dispose();
               
           }
    }//GEN-LAST:event_btSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCapa;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel ibCapa;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jCB_Nome;
    private javax.swing.JComboBox<String> jCB_Nome2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTF_Ano;
    private javax.swing.JTextField jTF_Duracao;
    private javax.swing.JTextField jTF_Filme;
    private javax.swing.JTextField jTF_codigo;
    private javax.swing.JTextField jTF_codigo2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField tfCapa;
    // End of variables declaration//GEN-END:variables

}
